name: Auto-format
on:
  push:
    branches:
      [task/27-create-github-action-to-auto-format-code]
      
jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 3.3.111304

      - name: Run dotnet format
        id: format
        run: dotnet format --no-restore

      - name: Commit files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m '${{ github.event.head_commit.message }} [auto-format]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.comment-branch.outputs.ref }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
